### ISSUE TITLE
GNSS not visible when not on USB     

### ISSUE THREAD

**Issue by Hydrsol** [Stefal/rtkbase#321]
In 2.3.x the GNSS can be added manual. I updated it to 2.4.1 and now the GNSS is not there. I choose the TTYACM0 port. Can you advice me. 

When i change the port to TTYS0 i will go to orange.

The GNSS outputs string matches the requirments set in this document.

It is connected to the serial port on the raspberry.

Do I have to edit something.

**Comment by Hydrsol** [comment]
![temp rtk base](https://github.com/Stefal/rtkbase/assets/88272809/9c850b3c-092e-4a91-aa74-c5eb9a39cdff)

**Comment by raven-worx** [comment]
i am also encountering the same behavior when using the Pi HAT (https://www.ardusimple.com/product/raspberry-adapter-for-simplertk2b/) (on /dev/serial0). I believe this is caused by ubxtool not recognizing the chip on a serial port?
I would also be glad to avoid the USB cable.

**Comment by Stefal** [comment]
RTKBase can't detect the F9P is the link isn't USB, you have to enter the correct port manually.
When done, you should see the sat level as with a usb link.

I will do a test on my side in the coming weeks.

**Comment by raven-worx** [comment]
Hmm, i tested again and now it worked for me (with the RPi HAT/adapter)
Cant tell why it didnt the first time i tried

**Comment by clint-qurrent** [comment]
I'm having the same issue. I've verified the serial data via minicom on the specified port. Everything looks good, but no satellites showing up in the status view and not getting any position data on ntrip.

Detect/Configure doesn't work properly, I'm assuming that is because it is expecting a USB device not a serial device.

Image and a portion of the diagnostic data.

![2023-06-28_12-40](https://github.com/Stefal/rtkbase/assets/65569387/fdf48079-f1cd-4f2c-85eb-fe56a2881c32)
[RTKBase_Diag.txt](https://github.com/Stefal/rtkbase/files/11899405/RTKBase_Diag.txt)
