### ISSUE TITLE
Will this repository work with reading USB ports of ublox reciever?

### ISSUE THREAD

**Issue by jehlijos** [Stefal/rtkbase#344]
Hi,
I am kind of new to GNSS technology. I am reading NMEA messages from ublox with python script on RaspberryPi (via PySerial). I need to find a way to connect this ublox to ntrip and also read data from USB port every second.
(https://github.com/jehlijos/GNSS-EGNOS-EDAS-public_copy)

I saw that ublox setting for this repository says "NMEA on USB out disabled". So my question is: Is it possible to set rtkbase to send ntrip to ublox while usb ports are used to send nmea messages to Raspberry (via python). Or are there any alternatives to make this work?

Thanks for any inputs in advance.

**Comment by Stefal** [comment]
You could enabled nmea and try to get the stream on tcp port 5015. You will get a mix of ubx and nmea data.

**Comment by geofis** [comment]
Apologies for the cross-posting and for re-opening this issue, but it might be relevant to mention the following here. Some time ago, when rtkbase was in version 2.3.1, I created my own fork (https://github.com/geofis/rtkbase), to which I added the ability to send RTCM corrections to the ZED-F9P, intending to use rtkbase as an "rtkrover." I made this change in the rtcm2rcv branch. If anyone finds it useful and would like to use this functionality, they would only need to review the changes in the rtcm2rcv branch of my repo and attempt the merge. I created a demonstrative video (in Spanish) of the mentioned functionality, which can be seen here (apologies for the poor quality): https://www.youtube.com/watch?v=xz_J4lrc160&t=165s.

Since rtkbase underwent a lot of development afterward, merging the specific branch would now be somewhat more complicated but not impossible. I left that functionality paused and never made a pull request because I am aware that rtkbase is designed for bases, not for rovers. In fact, I use an application I wrote myself in Bash to operate my GNSS receivers in rover mode, which works well, even on the Zero W, but I guess it is only intended for my use case. Initially, I used the Raspberry desktop, but later I created a headless version (in a branch with the same name), which is more versatile (https://github.com/geofis/BashRTKStation/tree/headless).
